### ISSUE TITLE
manual import cannot handle the symbol "!"

### ISSUE THREAD

**Issue by leftovernick** [binhex/arch-sonarr#12]
I had "Penn & Teller's Bullshit!" in my downloads folder. I was unable to load completed files and had to load each folder individually until I found the culprit. Any folder containing a file with a "!" cannot be read in Sonarr (it can in binhex-Radarr though). I have to go individually rename each file. Can this be fixed?

**Comment by binhex** [comment]
im not a sonarr developer, so you would need to post this as a github 'issue' on the sonarr repo, link below:-
https://github.com/Sonarr/Sonarr/issues
