### ISSUE TITLE
Any roadmap on when latest will be v3?

### ISSUE THREAD

**Issue by Xzas22** [binhex/arch-sonarr#14]
Just played with the radarr v3 update and its 10000x better UI and functionality. Is there a timeline or roadmap for sonarr:latest being rolled forward to v3 or do I need to specifically call out that version tag moving forward?

Thanks!

**Comment by binhex** [comment]
you need to ask the sonarr dev's this question, once v3 is released out of beta then it will be tagged as 'latest' for this image.
