### ISSUE TITLE
Sonarr v3 is released, sonarr aur package is updated

### ISSUE THREAD

**Issue by fryfrog** [binhex/arch-sonarr#17]
Hey @binhex, the ol' v3 has been *released* and I've updated the [sonarr](https://aur.archlinux.org/packages/sonarr/) package. I would suggest taking advantage of the new `package_info` which allows you to *disable* the built in updater and give your own message to users when there are updates available.

**Comment by fryfrog** [comment]
And it looks like automation just auto-fucked your `:latest` :(

**Comment by binhex** [comment]
all un-fucked! :-)
