### ISSUE TITLE
Indexers fail to connect regularly after update ~15th March 2019

### ISSUE THREAD

**Issue by Velicoma** [binhex/arch-sonarr#8]
Hi There,

Just under a month ago, I started noticing Sonarr not downloading shows, and advising that the indexers were not functioning. However, when I tested them in the settings, they all functioned fine. This led to Sonarr then working again for a few days, before the same thing happened.

I have attached a screen shot of the error, and an excerpt from the log. Happy to get any more detail I can assist with. Radarr is not having this issue (also a binhex docker).

Cheers!

[Issue log.txt](https://github.com/binhex/arch-sonarr/files/3063144/Issue.log.txt)
![image](https://user-images.githubusercontent.com/18582697/55869109-31965280-5bc9-11e9-8c1d-b59f1c8ee3fb.png)

**Comment by binhex** [comment]
hi im assuming you are the guy posting on the forum, sorry i probably wasn't explicit enough, i meant you need to post this issue on the sonarr github repo not this one. i dont author any of the applications so i cannot help you with issues to do with the application, for that you need to go to the applications repo, for this one its here:- https://github.com/Sonarr/Sonarr/issues
