### ISSUE TITLE
Indexers Unavailable due to failures

### ISSUE THREAD

**Issue by sinister718** [binhex/arch-sonarr#9]
Hello i am having the problem with my sonarr docker binhex-sonarr i consistently get the error indicated in the title every couple of hours i am using unraid with indexers added via jackett.
I also have radarr installed with indexers added from the same source and it never seems to have this issue. I'm not using any proxies with either container, i have gone as far as to to delete the container and start all over from scratch im not sure what the issue is but would love to resolve this months long issue i have been having

**Comment by binhex** [comment]
Thisi s most likely due to a failure of jackett to communicate with the index site, see link below for example:-
https://forums.sonarr.tv/t/all-indexers-are-unavailable-due-to-failures-help/17580

**Comment by JakeAi** [comment]
@sinister718  @binhex I have this issue as well. Radarr works no problem. Sonarr disables all my indexers randomly. Once every other day or so. The only fix is to restart Sonarr and then test them all one by one. Restarting Jackett doesn't fix anything.

**Comment by binhex** [comment]
@JakeAi  i would encourage you to post this as an 'issue' on the sonarr github repo then, just to be clear i dont have anything to do with development of sonarr, i simply package up what is available to me.
